### ISSUE TITLE
Linux Error : tkinter or tk?

### ISSUE THREAD

**Issue by ghost** [deepanharsha/DisCam#2]
When i Tried To Install Tkinter In My Linux Terminal
It Shows `module 'tkinter' not found`
When I Searched In Google For Any Other Solutions It Showed
Install tk so i did `pip install tk`.
Well, It Installed BUT..
the code where is `import tkinter as tk`
is not recognised as module tkinter rather tk so i did what anyone would do and changed "tkinter" to "tk"
so but next line error and fix not working. 

Fix Required/Solution Required.

Discam v1.1 on Zorin OS Lite
With Python 3.8.10 On Linux

Regards,
Assigned Testing Group "HDcodes"

**Comment by deepanharsha** [comment]
Hmm, Seems Like a Installation Problem of Some Sort. Will Try To Fix

**Comment by deepanharsha** [comment]
Sorry , But it worked Perfectly Fine On My Linux Test Machine
OS: LinuxMint 21.06 Victoria.
Tkinter Would Work Perfectly. No Problems
Please Provide More Inormation.
It is having chances that it's a Python-PIP Based Issue

**Comment by deepanharsha** [comment]
# This Issue Has Been Solved
**I have no answer for this because sufficient information was not provided**
**In The Latest Version Of Zorin (17.1) , I Was Not Able To Find The "Lite" Version , This indicates you're in a older version**
# Reasoning
- This Is Not My Problem As This Is A problem with **Your Specific Linux Distribution & Python PIP**
- Please Contact **Python Support Or Python Community Forums** As this is not a problem from My side
# Possible Fixes
- Just DO Not Use Zorin OS (It worked with Linuxmint perfectly)
- Update Your OS , The Latest Version Of Zorin OS is 17.1 (at the time of writing) And Is Available [Here](https://zorin.com/os/download/)
- You Could Try Using Other Package Managers (not reccommended)
- You Could Try Updating Your Python Version , The Latest Python Version is 3.12 , You're using Python 3.8.10. [You Can Download The Latest Python Version Here](https://www.python.org/downloads/)

# Any Other Issues?
**Contact Me On Instagram: @deepan_harsha**

**Comment by deepanharsha** [comment]
# Solution
- Update Your Python Version!!!
- tkinter is a included (mostly) library in Python! 
- Please Make Sure to have at least 3.10 running.
- If You cannot support it. Please Update Your OS1
# Solved!
This Issue has been solved successfully

**Comment by deepanharsha** [comment]
-completed-
